#!/usr/bin/env bash
#  a Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
    if [ $? -eq 0 ]; then
        echo "File transfer completed successfully."
    else
        echo "File transfer failed."
    fi
fi