#!/usr/bin/env bash

# installing nginx
sudo apt-get update
sudo apt-get -y install nginx

# allowing ngix on firewall
sudo ufw allow 'Nginx HTTP'
# Creating the 'Hello world' file
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo service nginx restart