#!/usr/bin/env bash
# Installing nginx on web-01
sudo apt-get update
sudo apt-get -y install nginx

# Allowing nginx in the firewall
sudo ufw allow 'Nginx HTTP'

# Creating the 'Hello world' file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Checking nginx configuration syntax
sudo nginx -t

# Starting nginx
sudo service nginx restart