#!/usr/bin/env bash
# redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
# allow ngix on firewall
sudo ufw allow 'Nginx HTTP'
# Creating the 'Hello world' file
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.x.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart