#!/usr/bin/env bash

# redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating the 'Hello world' file
echo "Hello, world" | sudo tee /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.x.com/ permanent;' /etc/nginx/sites-available/default

#restarting nginx
sudo service nginx restart