#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

# Install Nginx
sudo apt update
sudo apt install nginx
# Create a custom 404 error page with the desired content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Configure Nginx to use this custom 404 error page
sudo nano /etc/nginx/sites-available/default
error_page 404 /404.html;
sudo nginx -t
sudo systemctl reload nginx