#!/usr/bin/env bash
# Automating Nginx configuration

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Add the custom header within the http block in the Nginx configuration
sudo sed -i '/http {/a \    add_header X-Served-By $HOSTNAME;' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo systemctl restart nginx