#!/usr/bin/env bash
# Automating Nginx configuration

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# adding the custom header
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart