#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

# Updating packages and installing HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy config file
server_config="
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 249055-web-01 54.87.215.55:80 check
    server 249055-web-02 18.214.87.163:80 check
"

# Back up the original haproxy.cfg file
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# Replace the haproxy.cfg with the new configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable and restart the HAProxy service
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Verifying the status of HAProxy
sudo systemctl status haproxy
