#!/usr/bin/env bash
# Script to install and configure HAproxy on lb-01 server

# Updating packages and installing HAProxy on lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy config file
server_config=\
"
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 249055-web-01 54.87.215.55:80 check
    server 249055-web-02 18.214.87.163:80 check
"
# Append the server configuration to HAProxy config file
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart